build: false
environment:
  matrix:
    - TOXENV: "py27"
    - TOXENV: "py33"
    - TOXENV: "py34"
    - TOXENV: "flake827"
    - TOXENV: "flake834"
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install tox virtualenv"
test_script:
  - "c:\\python27\\Scripts\\tox --version"
  - "c:\\python27\\Scripts\\virtualenv --version"
  - "c:\\python27\\Scripts\\pip --version"
  - "c:\\python27\\Scripts\\tox"
